Revert "update_engine: Migrate build system to gyp."
This reverts commit 0d98d921d1ba82dc496bb98e7dedd4f3baaf67de.

Several canary bot (at least link, ivybridge, peach, beltino) failed with the following:

Generating delta update
Patching kernel /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/cros_generate_update_payload.dsXzrS
   into /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/src_image.bin
/dev/loop19 has been unmounted
rmdir: removing directory, `/tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/state.MtVYXo'
md5sum of src kernel:
84f3098b6822080aa2101f7623a8ebec  /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/cros_generate_update_payload.dsXzrS
md5sum of src root:
ed15fa4b6fab97b1d2704c109a95f366  /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/cros_generate_update_payload.S3qwDy
Patching kernel /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/cros_generate_update_payload.M1kqWN
   into /tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/tgt_image.bin
/dev/loop21 has been unmounted
rmdir: removing directory, `/tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/state.M80v7t'
Using rootfs partition size: 2147483648
ERROR: something wrong with flag 'old_dir' in file '../../../../../../tmp/portage/chromeos-base/update_engine-0.0.2-r646/work/update_engine-0.0.2/platform2/update_engine/payload_generator/generate_delta_main.cc'.  One possibility: file '../../../../../../dev/loop10 has been unmounted
rmdir: removing directory, `/tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/src_root.Amedwg'
/dev/loop5 has been unmounted
rmdir: removing directory, `/tmp/cbuildbot-tmpkZN69N/tmpXG3Fv3/paygen_payload.wqtif7/src_root.7rMVQV'
Cleanup success after an error.

This CL appears to be the only one related to the update_engine. Revert it first and see if the buildbot will recover.

Change-Id: Ia42b19a808ae9c95cd600e4f585adbf2e7511395
Reviewed-on: https://chromium-review.googlesource.com/208257
Reviewed-by: Chun-ta Lin <itspeter@chromium.org>
Commit-Queue: Chun-ta Lin <itspeter@chromium.org>
Tested-by: Chun-ta Lin <itspeter@chromium.org>